# Generated by Django 4.1 on 2023-01-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('smiles', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('given_name', models.CharField(blank=True, max_length=200, null=True)),
                ('family_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=200, null=True)),
                ('bio_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_bio_lead', to='example.person')),
                ('chem_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_chem_lead', to='example.person')),
                ('indication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='example.indication')),
                ('program_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_manager', to='example.person')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tissue', to='example.species')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein', to='example.gene')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein', to='example.species')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_milestone', to='example.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='example.protein'),
        ),
        migrations.CreateModel(
            name='Perturbation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('concentration_nm', models.IntegerField(blank=True, null=True)),
                ('compound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perturbation', to='example.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ', to='example.species')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gene', to='example.species'),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_duration', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('assay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment', to='example.assay')),
                ('bio_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_bio_lead', to='example.person')),
                ('perturbations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment', to='example.perturbation')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment', to='example.program')),
            ],
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_type', to='example.species')),
            ],
        ),
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_sex', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_age', models.IntegerField(blank=True, null=True)),
                ('donor_ethnicity', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_health_status', models.CharField(blank=True, max_length=200, null=True)),
                ('cell_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_line', to='example.celltype')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_line', to='example.indication')),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_line', to='example.organ')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_line', to='example.species')),
                ('tissue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_line', to='example.tissue')),
            ],
        ),
        migrations.AddField(
            model_name='assay',
            name='cell_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assay', to='example.cellline'),
        ),
        migrations.AddField(
            model_name='assay',
            name='for_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assay', to='example.program'),
        ),
    ]
