paths:
  docs_path: docs/
  ui_path: foam_ui/src/
  schema_path: foam_backend/example/

page_classes:
- name: RecordPage
  path: ./RecordPage.js
- name: ListPage
  path: ./ListPage.js

config_files:
- experiments.yaml
- gen_pages.yaml
